### ISSUE TITLE
Intermittently, prefix information isn't fully returned from "ot-ctl prefix" CLI command

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#468]
### **Describe the bug** A clear and concise description of what the bug is.

When using the CLI command "ot-ctl prefix", I have noticed that intermittently, I am lacking some of the information, as shown in this example where I have 3 prefixes configured.  Intermittently, I lose the first part of the information for the first prefix.  It seems to come and go.

```
pi@rpi1:~ $ sudo ot-ctl prefix
fdde:ad00:dead:beef::/64 paros med
fdde:ad03:0:0::/64 paros med
2001:22:0:0::/64 paros med
Done
pi@rpi1:~ $ sudo ot-ctl prefix
paros med
fdde:ad03:0:0::/64 paros med
2001:22:0:0::/64 paros med
Done
pi@rpi1:~ $ sudo ot-ctl prefix
paros med
fdde:ad03:0:0::/64 paros med
2001:22:0:0::/64 paros med
Done
pi@rpi1:~ $ sudo ot-ctl prefix
fdde:ad00:dead:beef::/64 paros med
fdde:ad03:0:0::/64 paros med
2001:22:0:0::/64 paros med
Done
pi@rpi1:~ $
```

### **To Reproduce** Information to reproduce the behavior, including:

I formed a thread network (of just the 1 node) using:
> ot-ctl channel 11
> ot-ctl networkname SilabsOpenThread
> ot-ctl panid 0xABCD
> ot-ctl extpanid DEAD00BEEF00CAFE
> ot-ctl masterkey 00112233445566778899AABBCCDDEEEE
> ot-ctl ifconfig up
> ot-ctl thread start

I verified the OTBR was in state "leader"
I added 3 prefixes to my OTBR:
> ot-ctl prefix add fdde:ad00:dead:beef::/64 paros med
> ot-ctl prefix add fdde:ad03::/64 paros med
> ot-ctl prefix add 2001:22::/64 paros med

I used the command "ot-ctl prefix" to view the configured prefixes multiple times and received differing results from each execution of the command.

### 1. Git commit id 
> commit c14ef63c07a788708f135cf5392854b4bc4d5e31

### 2. IEEE 802.15.4 hardware platform 
> Silabs BRD4161A

### 3. Build steps
> git clone https://github.com/openthread/ot-br-posix
> ./script/bootstrap
> NETWORK_MANAGER=0 ./script/setup
> Verified my device was using ttyACM0
> Configured /etc/default/otbr-agent with OTBR_AGENT_OPTS="-I wpan0 spinel+hdlc+uart:///dev/ttyACM0"
> Built an RCP for my device

### 4. Network topology
> Just the 1 device

### **Expected behavior** A clear and concise description of what you expected to happen.
> I think I should be getting a more consistent response from this CLI command.  Ideally the one with all 3 prefixes fully represented.

### **Console/log output** If applicable, add console/log output to help explain your problem.
> See above

**Comment by jwhui** [comment]
@JaneFromSilabs @gabekassel , just merged https://github.com/openthread/openthread/pull/5087, which should resolve this issue.

**Comment by JaneFromSilabs** [comment]
Hi @jwhui ,

I believe this is still failing for me, at least in the non-interactive mode.  The interactive mode is working just fine.  I am at:

`pi@rpi1:~/ot-br-posix $ git show
commit 591cfebbe1a337f84bc2549505e2fc42886ab4a6
Author: Yakun Xu <xyk@google.com>
Date:   Wed Jun 10 01:51:22 2020 +0800
`
Is this expected behavior if you are not interactive?

**Comment by jwhui** [comment]
@JaneFromSilabs , note that https://github.com/openthread/openthread/pull/5087 is a different repo and is a submodule of this repo. Can you ensure that `third_party/openthread` is up-to-date?
```
git submodule update --recurisve --depth 1
```

**Comment by JaneFromSilabs** [comment]
@jwhui , that worked, thank you!  Have a great weekend.  ~jane

**Comment by jwhui** [comment]
> @jwhui , that worked, thank you! Have a great weekend. ~jane

@JaneFromSilabs , great to hear!
